const allowedOrigins = [
  "https://kanpaiapp.com",
  "http://kanpaiapp.com",
  "http://referral.kanpaiapp.com",
  "http://remisiones.kanpaiapp.com",
  "https://referral.kanpaiapp.com",
  "https://remisiones.kanpaiapp.com",
  "kanpaiapp.com",
  "referral.kanpaiapp.com",
  "remisiones.kanpaiapp.com",
  "http://www.kanpaiapp.com",
  "https://www.kanpaiapp.com",
  "https://driver.kanpaiapp.com",
  "https://supplier.kanpaiapp.com",
  "https://admin.kanpaiapp.com",
  "https://kanpai-referral.vercel.app",
  "https://kanpai-delivery.vercel.app",
  "https://kanpai-seller.vercel.app",
  "https://kampai.vercel.app",
  "http://localhost:3000",
  "http://localhost:3001",
  "http://localhost:3002", 
  "http://localhost:5173", 
  "https://kanpai-english.netlify.app",
  "http://127.0.0.1:5173",
  "https://kanpai-english.vercel.app",
 ];
 
 module.exports = allowedOrigins;